before_script:
  - echo "begin"

after_script:
  - echo "completed!"
  
pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r docs/. public/
    - ls public
    - echo "deploy ok"
  artifacts:
    paths:
    - public
  tags:
    - shell
