before_script:
  - echo "begin"

after_script:
  - echo "completed!"
  
pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r docs/. public
    - echo `ls public`
  artifacts:
    paths:
    - public