before_script:
  - echo "begin"

after_script:
  - echo "completed!"
  
pages:
  stage: deploy
  script:
    - mkdir public
    # for linux bash
    #- cp -r docs/. public
    # for window powershell
    - cp docs/* public
    - ls public
    - echo "deploy ok"
  artifacts:
    paths:
    - public
  tags:
    - shell
