before_script:
  - echo "begin"

after_script:
  - echo "completed!"
  
deploy:
  stage: deploy
  script:
    - mkdir .public
    - cp -r . .public
    - mv .public public
    - echo `ls public`
  artifacts:
    paths:
    - public